replicaCount: 1
terminationGracePeriod: 60

image:
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  externalIPs:
  - '192.168.1.75'
  
ports:
  - name: radarr-web
    containerPort: 7878
    targetPort: 7878
    protocol: TCP

affinity: {}
nodeSelector: {}

storageConfig:
  storageClassName: synology-iscsi
  reclaimPolicy: Retain
  volumeName: ""
  volumeMode: Filesystem
  volumeSize: 10Gi
  accessModes:
    - ReadWriteOnce